"""
mp3_to_c.py - MP3 파일들을 C 배열(Flash 내장용)로 변환

사용법: python3 build-tools/mp3_to_c.py

입력:  세팅_음성파일_24k/*.mp3  (01.mp3 ~ 33.mp3)
출력:  MINIMP3/flash_audio/src/mp3_flash_data.c
       MINIMP3/flash_audio/inc/mp3_flash_data.h
"""

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)

MP3_DIR = os.path.join(PROJECT_DIR, "세팅_음성파일_48k")
OUT_C   = os.path.join(PROJECT_DIR, "MINIMP3", "flash_audio", "src", "mp3_flash_data.c")
OUT_H   = os.path.join(PROJECT_DIR, "MINIMP3", "flash_audio", "inc", "mp3_flash_data.h")

NUM_FILES = 33

def mp3_to_c():
    os.makedirs(os.path.dirname(OUT_C), exist_ok=True)
    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)

    # 파일 로드
    files = []
    for i in range(1, NUM_FILES + 1):
        path = os.path.join(MP3_DIR, f"{i:02d}.mp3")
        if not os.path.exists(path):
            print(f"ERROR: {path} not found", file=sys.stderr)
            sys.exit(1)
        with open(path, "rb") as f:
            data = f.read()
        files.append((i, data))
        print(f"  {i:02d}.mp3  {len(data):6d} bytes")

    total = sum(len(d) for _, d in files)
    print(f"\n  총합: {total} bytes ({total//1024} KB)\n")

    # .h 생성
    with open(OUT_H, "w") as h:
        h.write("/* Auto-generated by build-tools/mp3_to_c.py — DO NOT EDIT */\n")
        h.write("#pragma once\n")
        h.write("#include <stdint.h>\n\n")
        h.write(f"#define MP3_FLASH_NUM_FILES  {NUM_FILES}\n\n")
        for i, data in files:
            h.write(f"extern const uint8_t  mp3_flash_{i:02d}[];\n")
            h.write(f"extern const uint32_t mp3_flash_{i:02d}_size;\n")
        h.write("\n")
        h.write("/* Lookup tables indexed by [file_num - 1] */\n")
        h.write("extern const uint8_t  * const mp3_flash_data[MP3_FLASH_NUM_FILES];\n")
        h.write("extern const uint32_t         mp3_flash_size[MP3_FLASH_NUM_FILES];\n")

    # .c 생성
    with open(OUT_C, "w") as c:
        c.write("/* Auto-generated by build-tools/mp3_to_c.py — DO NOT EDIT */\n")
        c.write('#include "mp3_flash_data.h"\n\n')

        for i, data in files:
            c.write(f"/* {i:02d}.mp3  ({len(data)} bytes) */\n")
            c.write(f"const uint32_t mp3_flash_{i:02d}_size = {len(data)}U;\n")
            c.write(f"const uint8_t  mp3_flash_{i:02d}[] __attribute__((aligned(4))) = {{\n")
            # 16 bytes per line
            for off in range(0, len(data), 16):
                chunk = data[off:off+16]
                line = ", ".join(f"0x{b:02X}" for b in chunk)
                c.write(f"    {line},\n")
            c.write("};\n\n")

        # lookup tables
        c.write("const uint8_t * const mp3_flash_data[MP3_FLASH_NUM_FILES] = {\n")
        for i, _ in files:
            c.write(f"    mp3_flash_{i:02d},\n")
        c.write("};\n\n")

        c.write("const uint32_t mp3_flash_size[MP3_FLASH_NUM_FILES] = {\n")
        for i, data in files:
            c.write(f"    {len(data)}U,  /* {i:02d}.mp3 */\n")
        c.write("};\n")

    print(f"Generated:\n  {OUT_H}\n  {OUT_C}")


if __name__ == "__main__":
    mp3_to_c()
