/* Auto-generated by build-tools/mp3_to_c.py — DO NOT EDIT */
#pragma once
#include <stdint.h>

#define MP3_FLASH_NUM_FILES  33

extern const uint8_t  mp3_flash_01[];
extern const uint32_t mp3_flash_01_size;
extern const uint8_t  mp3_flash_02[];
extern const uint32_t mp3_flash_02_size;
extern const uint8_t  mp3_flash_03[];
extern const uint32_t mp3_flash_03_size;
extern const uint8_t  mp3_flash_04[];
extern const uint32_t mp3_flash_04_size;
extern const uint8_t  mp3_flash_05[];
extern const uint32_t mp3_flash_05_size;
extern const uint8_t  mp3_flash_06[];
extern const uint32_t mp3_flash_06_size;
extern const uint8_t  mp3_flash_07[];
extern const uint32_t mp3_flash_07_size;
extern const uint8_t  mp3_flash_08[];
extern const uint32_t mp3_flash_08_size;
extern const uint8_t  mp3_flash_09[];
extern const uint32_t mp3_flash_09_size;
extern const uint8_t  mp3_flash_10[];
extern const uint32_t mp3_flash_10_size;
extern const uint8_t  mp3_flash_11[];
extern const uint32_t mp3_flash_11_size;
extern const uint8_t  mp3_flash_12[];
extern const uint32_t mp3_flash_12_size;
extern const uint8_t  mp3_flash_13[];
extern const uint32_t mp3_flash_13_size;
extern const uint8_t  mp3_flash_14[];
extern const uint32_t mp3_flash_14_size;
extern const uint8_t  mp3_flash_15[];
extern const uint32_t mp3_flash_15_size;
extern const uint8_t  mp3_flash_16[];
extern const uint32_t mp3_flash_16_size;
extern const uint8_t  mp3_flash_17[];
extern const uint32_t mp3_flash_17_size;
extern const uint8_t  mp3_flash_18[];
extern const uint32_t mp3_flash_18_size;
extern const uint8_t  mp3_flash_19[];
extern const uint32_t mp3_flash_19_size;
extern const uint8_t  mp3_flash_20[];
extern const uint32_t mp3_flash_20_size;
extern const uint8_t  mp3_flash_21[];
extern const uint32_t mp3_flash_21_size;
extern const uint8_t  mp3_flash_22[];
extern const uint32_t mp3_flash_22_size;
extern const uint8_t  mp3_flash_23[];
extern const uint32_t mp3_flash_23_size;
extern const uint8_t  mp3_flash_24[];
extern const uint32_t mp3_flash_24_size;
extern const uint8_t  mp3_flash_25[];
extern const uint32_t mp3_flash_25_size;
extern const uint8_t  mp3_flash_26[];
extern const uint32_t mp3_flash_26_size;
extern const uint8_t  mp3_flash_27[];
extern const uint32_t mp3_flash_27_size;
extern const uint8_t  mp3_flash_28[];
extern const uint32_t mp3_flash_28_size;
extern const uint8_t  mp3_flash_29[];
extern const uint32_t mp3_flash_29_size;
extern const uint8_t  mp3_flash_30[];
extern const uint32_t mp3_flash_30_size;
extern const uint8_t  mp3_flash_31[];
extern const uint32_t mp3_flash_31_size;
extern const uint8_t  mp3_flash_32[];
extern const uint32_t mp3_flash_32_size;
extern const uint8_t  mp3_flash_33[];
extern const uint32_t mp3_flash_33_size;

/* Lookup tables indexed by [file_num - 1] */
extern const uint8_t  * const mp3_flash_data[MP3_FLASH_NUM_FILES];
extern const uint32_t         mp3_flash_size[MP3_FLASH_NUM_FILES];
